version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - rabbit-data:/var/lib/rabbitmq/
            - rabbit-log:/var/log/rabbitmq

volumes:
  rabbit-data:
  rabbit-log: