version: '3.9'

services:
    rabbitmq3:
        container_name: rabbitmq-notification
        image: rabbitmq:3.8-management-alpine
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - rabbit-data:/var/lib/rabbitmq/
            - rabbit-log:/var/log/rabbitmq

    db:
        container_name: postgres-notification
        image: postgres:13
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        ports:
          - '5432:5432'
        env_file:
          - .env

volumes:
  rabbit-data:
  rabbit-log:
  postgres_data:
    name: postgres_data
