create_notification = "INSERT INTO notification (created_at, updated_at, template_id, role) VALUES(%s, %s, %s, %s) RETURNING id"
create_history = "INSERT INTO history (created_at, notification_id, status) VALUES(%s, %s, %s) RETURNING id"
check_task = "SELECT id FROM task WHERE created_at <= %s and status = 'created'"
change_task_status = "UPDATE task SET status = %s WHERE notification_id = %s RETURNING id"
get_notification_data = "SELECT id, template_params, role, permission, email FROM public.notification WHERE id = %s"
get_template_path = "SELECT path FROM public.template WHERE id = %s"
get_notification_id_in_task = "SELECT notification_id FROM public.task WHERE id = %s"
